#define yy_create_buffer plpgsql_base_yy_create_buffer
#define yy_delete_buffer plpgsql_base_yy_delete_buffer
#define yy_scan_buffer plpgsql_base_yy_scan_buffer
#define yy_scan_string plpgsql_base_yy_scan_string
#define yy_scan_bytes plpgsql_base_yy_scan_bytes
#define yy_flex_debug plpgsql_base_yy_flex_debug
#define yy_init_buffer plpgsql_base_yy_init_buffer
#define yy_flush_buffer plpgsql_base_yy_flush_buffer
#define yy_load_buffer_state plpgsql_base_yy_load_buffer_state
#define yy_switch_to_buffer plpgsql_base_yy_switch_to_buffer
#define yyin plpgsql_base_yyin
#define yyleng plpgsql_base_yyleng
#define yylex plpgsql_base_yylex
#define yyout plpgsql_base_yyout
#define yyrestart plpgsql_base_yyrestart
#define yytext plpgsql_base_yytext

#line 19 "pl_scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * /master/usr.bin/lex/skel.c,v 1.3 1997/09/25 00:10:23 jch Exp
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else							/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST
#endif   /* __STDC__ */
#endif   /* ! __cplusplus */

#ifdef __TURBOC__
#pragma warn -rch
#pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int	yyleng;
extern FILE *yyin,
		   *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).	This
 * avoids problems with code like:
 *
 *	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
{
	FILE	   *yy_input_file;

	char	   *yy_ch_buf;		/* input buffer */
	char	   *yy_buf_pos;		/* current position in input buffer */

	/*
	 * Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t	yy_buf_size;

	/*
	 * Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int			yy_n_chars;

	/*
	 * Whether we "own" the buffer - i.e., we know we created it, and can
	 * realloc() it to grow it, and should free() it to delete it.
	 */
	int			yy_is_our_buffer;

	/*
	 * Whether this is an "interactive" input source; if so, and if we're
	 * using stdio for input, then we want to use getc() instead of
	 * fread(), to make sure we stop fetching input after each newline.
	 */
	int			yy_is_interactive;

	/*
	 * Whether we're considered to be at the beginning of a line. If so,
	 * '^' rules will be active on the next match, otherwise not.
	 */
	int			yy_at_bol;

	/*
	 * Whether to try to fill the input buffer when we reach the end of
	 * it.
	 */
	int			yy_fill_buffer;

	int			yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1

	/*
	 * When an EOF's been seen but there's still some text to process then
	 * we mark the buffer as YY_EOF_PENDING, to indicate that we shouldn't
	 * try reading from the input source any more.	We might still have a
	 * bunch of tokens to match, though, because of possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new" (via
	 * yyrestart()), so that the user can continue scanning by just
	 * pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int	yy_n_chars;			/* number of characters read into
								 * yy_ch_buf */


int			yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int	yy_init = 1;		/* whether we need to initialize */
static int	yy_start = 0;		/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.	A bit of a hack ...
 */
static int	yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO((FILE *input_file));

void yy_switch_to_buffer YY_PROTO((YY_BUFFER_STATE new_buffer));
void yy_load_buffer_state YY_PROTO((void));
YY_BUFFER_STATE yy_create_buffer YY_PROTO((FILE *file, int size));
void yy_delete_buffer YY_PROTO((YY_BUFFER_STATE b));
void yy_init_buffer YY_PROTO((YY_BUFFER_STATE b, FILE *file));
void yy_flush_buffer YY_PROTO((YY_BUFFER_STATE b));

#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO((char *base, yy_size_t size));
YY_BUFFER_STATE yy_scan_string YY_PROTO((yyconst char *yy_str));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO((yyconst char *bytes, int len));

static void *yy_flex_alloc YY_PROTO((yy_size_t));
static void *yy_flex_realloc YY_PROTO((void *, yy_size_t));
static void yy_flex_free YY_PROTO((void *));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE	   *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;

#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO((void));
static yy_state_type yy_try_NUL_trans YY_PROTO((yy_state_type current_state));
static int yy_get_next_buffer YY_PROTO((void));
static void yy_fatal_error YY_PROTO((yyconst char msg[]));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[338] =
{0,
	0, 0, 80, 80, 0, 0, 83, 81, 70, 70,
	81, 81, 76, 81, 81, 81, 68, 81, 2, 52,
	52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
	52, 52, 52, 52, 52, 52, 81, 80, 79, 82,
	75, 74, 75, 70, 69, 0, 52, 60, 71, 3,
	72, 68, 1, 0, 52, 0, 0, 52, 52, 52,
	52, 52, 52, 52, 52, 52, 52, 52, 52, 52,
	52, 52, 23, 24, 27, 52, 52, 52, 52, 52,
	52, 52, 52, 52, 52, 52, 45, 52, 52, 52,
	0, 80, 78, 77, 73, 52, 0, 0, 0, 0,

	71, 0, 0, 0, 0, 53, 52, 52, 52, 52,
	52, 52, 52, 52, 52, 52, 52, 15, 52, 52,
	52, 52, 20, 52, 22, 52, 52, 28, 52, 52,
	31, 52, 52, 52, 52, 52, 52, 52, 52, 52,
	52, 52, 52, 52, 52, 52, 52, 0, 0, 0,
	0, 0, 61, 0, 0, 0, 53, 0, 53, 0,
	0, 52, 52, 52, 52, 52, 52, 52, 52, 52,
	51, 13, 52, 52, 52, 18, 52, 21, 25, 26,
	29, 30, 52, 33, 34, 52, 52, 52, 52, 52,
	52, 52, 52, 52, 44, 46, 52, 48, 52, 0,

	0, 0, 0, 61, 0, 61, 0, 0, 0, 0,
	0, 0, 0, 0, 54, 4, 5, 6, 52, 52,
	9, 52, 52, 52, 14, 52, 52, 19, 52, 52,
	36, 52, 52, 52, 52, 52, 52, 52, 52, 49,
	0, 0, 0, 0, 0, 0, 0, 62, 0, 55,
	0, 0, 0, 54, 0, 54, 0, 52, 8, 52,
	52, 52, 52, 52, 32, 52, 37, 38, 52, 40,
	52, 52, 43, 52, 0, 0, 63, 0, 0, 0,
	62, 0, 62, 0, 0, 0, 0, 0, 52, 10,
	11, 52, 52, 17, 35, 52, 41, 52, 47, 50,

	0, 0, 0, 0, 0, 0, 56, 0, 7, 52,
	52, 52, 52, 0, 0, 64, 0, 58, 0, 0,
	52, 16, 52, 42, 66, 0, 0, 0, 57, 52,
	39, 0, 65, 59, 12, 67, 0
};

static yyconst int yy_ec[256] =
{0,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
	1, 2, 4, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 1, 5, 6, 7, 8, 1, 9, 1,
	1, 10, 1, 1, 11, 12, 13, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 15, 1, 1,
	16, 1, 1, 1, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 28, 29, 30, 31, 32, 33,
	28, 34, 35, 36, 37, 38, 39, 40, 41, 28,
	1, 17, 1, 1, 18, 1, 19, 20, 21, 22,

	23, 24, 25, 26, 27, 28, 28, 29, 30, 31,
	32, 33, 28, 34, 35, 36, 37, 38, 39, 40,
	41, 28, 1, 1, 1, 1, 1, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,

	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28
};

static yyconst int yy_meta[42] =
{0,
	1, 2, 3, 4, 5, 1, 6, 6, 7, 1,
	1, 8, 1, 6, 1, 1, 7, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2
};

static yyconst short int yy_base[358] =
{0,
	0, 432, 33, 34, 42, 43, 435, 1273, 45, 52,
	54, 417, 1273, 418, 407, 403, 396, 393, 1273, 58,
	61, 72, 94, 54, 72, 76, 56, 87, 88, 98,
	100, 111, 122, 115, 124, 138, 374, 0, 394, 0,
	1273, 1273, 387, 169, 394, 380, 174, 181, 0, 1273,
	1273, 370, 1273, 188, 126, 53, 199, 178, 137, 177,
	187, 188, 206, 202, 212, 216, 218, 231, 200, 227,
	233, 237, 243, 247, 249, 260, 258, 264, 262, 279,
	275, 286, 303, 288, 299, 314, 313, 315, 324, 336,
	350, 0, 1273, 1273, 1273, 367, 376, 374, 58, 385,

	0, 348, 333, 389, 362, 393, 379, 375, 325, 385,
	386, 395, 396, 407, 405, 414, 425, 421, 432, 438,
	436, 442, 448, 452, 454, 458, 464, 465, 471, 477,
	478, 487, 489, 493, 499, 500, 514, 510, 512, 525,
	527, 529, 536, 540, 547, 551, 557, 330, 332, 314,
	588, 344, 593, 294, 297, 324, 604, 611, 618, 163,
	629, 606, 608, 619, 617, 615, 630, 631, 629, 640,
	641, 647, 651, 653, 660, 662, 669, 671, 673, 675,
	682, 684, 688, 686, 695, 697, 699, 701, 710, 712,
	714, 721, 731, 733, 727, 737, 744, 743, 754, 299,

	283, 288, 314, 785, 792, 799, 177, 810, 278, 287,
	274, 264, 814, 298, 596, 791, 792, 793, 807, 803,
	809, 813, 819, 820, 826, 830, 832, 841, 842, 843,
	852, 854, 864, 863, 873, 853, 874, 880, 889, 890,
	256, 246, 254, 235, 216, 926, 241, 930, 192, 1273,
	189, 190, 207, 937, 944, 947, 172, 925, 929, 936,
	935, 945, 949, 956, 955, 965, 967, 969, 971, 978,
	982, 980, 984, 993, 167, 153, 1273, 149, 154, 176,
	1024, 1031, 1034, 144, 135, 124, 126, 105, 1011, 1012,
	1021, 1023, 1025, 1032, 1034, 1036, 1038, 1045, 1049, 1273,

	109, 103, 113, 87, 92, 73, 1273, 74, 1051, 1058,
	1060, 1067, 1069, 77, 41, 1273, 45, 1273, 39, 48,
	1079, 1078, 1080, 1089, 1273, 35, 44, 35, 1273, 1090,
	1091, 21, 1273, 1273, 1100, 1273, 1273, 1137, 1145, 1153,
	1160, 1168, 1176, 1184, 1192, 1199, 1203, 1208, 1215, 1223,
	1230, 1237, 1241, 1246, 1253, 1259, 1266
};

static yyconst short int yy_def[358] =
{0,
	337, 1, 338, 338, 339, 339, 337, 337, 337, 337,
	340, 337, 337, 337, 337, 337, 337, 337, 337, 341,
	341, 341, 341, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 337, 342, 337, 343,
	337, 337, 337, 337, 344, 344, 337, 337, 345, 337,
	337, 337, 337, 337, 23, 337, 346, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	337, 342, 337, 337, 337, 337, 344, 337, 337, 347,

	345, 337, 337, 346, 348, 349, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 337, 337, 337,
	347, 350, 351, 337, 337, 348, 337, 337, 349, 337,
	352, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 337,

	337, 337, 350, 337, 337, 351, 337, 353, 337, 337,
	337, 337, 352, 354, 355, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	337, 337, 337, 337, 337, 353, 356, 357, 337, 337,
	337, 337, 354, 337, 337, 355, 337, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 337, 337, 337, 337, 337, 356,
	337, 337, 357, 337, 337, 337, 337, 337, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 337,

	337, 337, 337, 337, 337, 337, 337, 337, 23, 23,
	23, 23, 23, 337, 337, 337, 337, 337, 337, 337,
	23, 23, 23, 23, 337, 337, 337, 337, 337, 23,
	23, 337, 337, 337, 23, 337, 0, 337, 337, 337,
	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337, 337, 337, 337
};

static yyconst short int yy_nxt[1315] =
{0,
	8, 9, 10, 9, 11, 8, 12, 8, 13, 8,
	14, 15, 16, 17, 18, 19, 8, 20, 21, 22,
	23, 24, 25, 26, 27, 20, 28, 20, 29, 20,
	30, 31, 32, 33, 34, 35, 20, 20, 36, 20,
	20, 39, 39, 336, 42, 42, 44, 44, 44, 40,
	40, 43, 43, 44, 44, 44, 46, 334, 47, 54,
	54, 54, 54, 54, 54, 56, 333, 332, 56, 57,
	329, 328, 57, 54, 54, 54, 63, 327, 72, 56,
	64, 326, 55, 57, 55, 55, 102, 55, 103, 58,
	65, 149, 55, 150, 59, 54, 54, 54, 69, 325,

	66, 56, 67, 55, 55, 57, 320, 70, 55, 71,
	73, 68, 55, 319, 318, 55, 55, 74, 55, 76,
	77, 75, 60, 55, 55, 61, 55, 317, 55, 78,
	62, 55, 80, 81, 79, 316, 55, 85, 315, 55,
	82, 314, 55, 55, 83, 308, 55, 55, 307, 86,
	55, 55, 55, 84, 55, 87, 89, 55, 55, 306,
	55, 108, 55, 90, 88, 55, 55, 305, 55, 55,
	44, 44, 44, 55, 55, 54, 54, 54, 97, 304,
	281, 56, 98, 98, 98, 57, 303, 302, 99, 54,
	54, 54, 100, 301, 48, 56, 211, 300, 212, 57,

	104, 104, 104, 105, 107, 55, 55, 288, 109, 55,
	244, 254, 245, 55, 55, 55, 55, 110, 55, 55,
	115, 111, 287, 55, 55, 112, 113, 286, 55, 114,
	55, 55, 285, 55, 55, 122, 55, 55, 55, 118,
	55, 116, 55, 55, 55, 281, 55, 55, 55, 55,
	117, 119, 55, 120, 55, 55, 279, 121, 55, 55,
	123, 55, 55, 55, 124, 55, 278, 55, 55, 55,
	126, 55, 125, 55, 55, 55, 277, 55, 55, 55,
	55, 276, 127, 55, 128, 55, 55, 275, 55, 55,
	132, 129, 55, 55, 55, 55, 55, 130, 55, 131,

	55, 133, 254, 55, 252, 251, 55, 55, 134, 250,
	55, 55, 135, 249, 55, 55, 55, 55, 204, 55,
	243, 242, 55, 136, 55, 241, 141, 142, 157, 210,
	55, 55, 209, 137, 55, 55, 143, 138, 139, 55,
	140, 55, 55, 55, 55, 55, 55, 144, 204, 55,
	55, 55, 55, 55, 202, 55, 55, 145, 146, 164,
	55, 55, 147, 201, 55, 200, 157, 55, 54, 54,
	54, 97, 55, 155, 56, 98, 98, 98, 57, 154,
	96, 99, 148, 52, 96, 100, 151, 151, 151, 152,
	104, 104, 104, 105, 158, 158, 158, 162, 96, 95,

	160, 163, 93, 55, 161, 91, 55, 55, 53, 52,
	55, 55, 51, 55, 55, 55, 55, 55, 50, 165,
	166, 55, 55, 55, 168, 169, 55, 55, 49, 170,
	48, 167, 55, 55, 337, 55, 55, 37, 55, 337,
	337, 55, 55, 55, 337, 55, 171, 172, 337, 55,
	55, 173, 55, 55, 174, 337, 55, 55, 175, 337,
	55, 55, 177, 55, 55, 337, 55, 55, 55, 55,
	55, 176, 55, 55, 55, 337, 55, 337, 55, 55,
	55, 178, 55, 55, 55, 55, 55, 337, 55, 179,
	55, 337, 55, 55, 55, 180, 55, 337, 337, 55,

	55, 55, 55, 181, 183, 55, 55, 55, 55, 55,
	337, 337, 182, 55, 55, 184, 186, 55, 55, 185,
	55, 55, 337, 55, 55, 55, 337, 55, 55, 55,
	55, 188, 189, 187, 337, 55, 55, 337, 55, 337,
	55, 55, 55, 55, 193, 55, 190, 192, 191, 337,
	55, 194, 337, 55, 337, 55, 55, 55, 55, 337,
	55, 55, 196, 55, 55, 55, 195, 55, 55, 337,
	337, 55, 55, 337, 337, 55, 55, 197, 55, 55,
	337, 198, 55, 55, 337, 199, 337, 55, 55, 151,
	151, 151, 152, 55, 205, 205, 205, 255, 255, 255,

	207, 337, 337, 257, 208, 158, 158, 158, 105, 337,
	337, 160, 158, 158, 158, 161, 337, 337, 160, 158,
	158, 158, 161, 337, 337, 160, 337, 337, 337, 161,
	213, 213, 213, 214, 55, 337, 55, 55, 217, 55,
	216, 218, 55, 55, 55, 55, 220, 55, 55, 222,
	55, 55, 219, 55, 221, 55, 337, 55, 55, 55,
	55, 55, 55, 337, 337, 223, 55, 55, 55, 55,
	224, 55, 55, 337, 225, 55, 55, 55, 55, 55,
	337, 55, 55, 55, 55, 226, 337, 55, 55, 55,
	55, 55, 337, 55, 228, 337, 227, 55, 55, 55,

	55, 55, 55, 55, 55, 55, 55, 55, 229, 55,
	55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
	55, 231, 55, 55, 55, 55, 55, 55, 230, 55,
	55, 55, 55, 55, 232, 55, 337, 55, 55, 233,
	234, 55, 55, 55, 337, 55, 55, 235, 55, 55,
	55, 237, 55, 238, 236, 55, 337, 55, 55, 55,
	337, 55, 55, 55, 55, 55, 337, 55, 55, 55,
	239, 55, 55, 55, 55, 55, 240, 337, 337, 55,
	55, 337, 55, 337, 337, 55, 205, 205, 205, 152,
	55, 337, 207, 205, 205, 205, 208, 337, 337, 207,

	205, 205, 205, 208, 337, 337, 207, 337, 337, 337,
	208, 246, 246, 246, 247, 213, 213, 213, 214, 55,
	55, 55, 55, 55, 55, 258, 337, 55, 55, 55,
	337, 55, 337, 337, 55, 55, 259, 55, 55, 55,
	55, 55, 337, 55, 55, 55, 260, 261, 55, 55,
	55, 262, 337, 337, 55, 55, 55, 55, 55, 337,
	55, 55, 55, 55, 265, 263, 55, 264, 55, 55,
	55, 55, 55, 55, 55, 267, 266, 55, 55, 55,
	55, 55, 55, 55, 55, 55, 268, 271, 55, 55,
	55, 55, 55, 337, 55, 55, 337, 337, 269, 55,

	55, 55, 55, 270, 55, 272, 337, 337, 55, 55,
	55, 55, 337, 337, 337, 273, 55, 55, 55, 274,
	55, 55, 337, 337, 337, 55, 55, 246, 246, 246,
	247, 282, 282, 282, 337, 337, 337, 284, 255, 255,
	255, 214, 337, 337, 257, 255, 255, 255, 255, 255,
	255, 257, 337, 55, 257, 289, 55, 55, 290, 337,
	55, 55, 337, 55, 55, 55, 55, 55, 337, 337,
	291, 55, 55, 55, 337, 293, 55, 55, 294, 292,
	55, 55, 337, 55, 55, 55, 55, 55, 296, 337,
	337, 55, 55, 55, 295, 55, 55, 55, 55, 55,

	55, 55, 55, 55, 297, 55, 55, 55, 55, 55,
	55, 55, 55, 55, 55, 55, 298, 299, 55, 337,
	55, 55, 337, 337, 55, 282, 282, 282, 247, 55,
	337, 284, 282, 282, 282, 282, 282, 282, 284, 55,
	55, 284, 55, 55, 337, 337, 309, 55, 55, 55,
	337, 55, 55, 55, 55, 337, 311, 55, 310, 55,
	55, 55, 55, 55, 55, 55, 55, 312, 55, 55,
	55, 337, 55, 55, 55, 313, 55, 55, 337, 55,
	55, 55, 55, 337, 321, 55, 55, 55, 55, 55,
	322, 55, 337, 323, 55, 55, 55, 55, 55, 330,

	55, 331, 337, 55, 324, 55, 55, 55, 55, 55,
	55, 55, 337, 337, 55, 55, 55, 55, 55, 55,
	55, 55, 55, 337, 335, 55, 55, 55, 55, 337,
	337, 55, 337, 337, 337, 337, 55, 38, 38, 38,
	38, 38, 38, 38, 38, 41, 41, 41, 41, 41,
	41, 41, 41, 45, 45, 45, 45, 45, 45, 45,
	45, 55, 55, 55, 337, 55, 337, 55, 92, 92,
	92, 92, 92, 92, 337, 92, 94, 94, 337, 94,
	94, 94, 94, 94, 46, 46, 46, 46, 46, 46,
	46, 46, 101, 101, 337, 337, 101, 101, 101, 101,

	106, 106, 106, 106, 153, 153, 153, 153, 156, 156,
	156, 156, 156, 156, 156, 156, 159, 159, 159, 337,
	159, 337, 159, 203, 203, 203, 203, 203, 203, 203,
	203, 206, 206, 206, 337, 206, 337, 206, 215, 215,
	215, 215, 248, 248, 248, 248, 253, 253, 253, 253,
	253, 253, 253, 253, 256, 256, 256, 337, 256, 280,
	280, 280, 280, 280, 280, 280, 280, 283, 283, 283,
	337, 283, 7, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,

	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337
};

static yyconst short int yy_chk[1315] =
{0,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 4, 332, 5, 6, 9, 9, 9, 3,
	4, 5, 6, 10, 10, 10, 11, 328, 11, 20,
	20, 20, 21, 21, 21, 20, 327, 326, 21, 20,
	320, 319, 21, 22, 22, 22, 24, 317, 27, 22,
	24, 315, 24, 22, 27, 24, 56, 27, 56, 21,
	24, 99, 27, 99, 22, 23, 23, 23, 26, 314,

	25, 23, 25, 25, 26, 23, 308, 26, 25, 26,
	28, 25, 26, 306, 305, 28, 29, 28, 28, 29,
	30, 28, 23, 28, 29, 23, 30, 304, 31, 30,
	23, 31, 31, 32, 30, 303, 31, 34, 302, 32,
	33, 301, 32, 34, 33, 288, 34, 32, 287, 35,
	33, 34, 35, 33, 55, 35, 36, 55, 33, 286,
	35, 59, 55, 36, 35, 59, 36, 285, 59, 36,
	44, 44, 44, 59, 36, 47, 47, 47, 47, 284,
	280, 47, 48, 48, 48, 47, 279, 278, 48, 54,
	54, 54, 48, 276, 48, 54, 160, 275, 160, 54,

	57, 57, 57, 57, 58, 60, 58, 257, 60, 58,
	207, 253, 207, 60, 58, 61, 62, 61, 61, 62,
	64, 62, 252, 61, 62, 63, 63, 251, 69, 63,
	64, 69, 249, 64, 63, 69, 69, 63, 64, 67,
	65, 65, 63, 65, 66, 247, 67, 66, 65, 67,
	66, 68, 66, 68, 67, 70, 245, 68, 70, 68,
	70, 71, 68, 70, 71, 72, 244, 68, 72, 71,
	74, 73, 72, 72, 73, 74, 243, 75, 74, 73,
	75, 242, 74, 74, 76, 75, 77, 241, 76, 77,
	79, 76, 78, 79, 77, 78, 76, 77, 79, 78,

	78, 80, 214, 81, 212, 211, 81, 80, 81, 210,
	80, 81, 82, 209, 82, 80, 84, 82, 203, 84,
	202, 201, 82, 83, 84, 200, 84, 85, 156, 155,
	85, 83, 154, 83, 83, 85, 86, 83, 83, 83,
	83, 87, 86, 88, 87, 86, 88, 88, 152, 87,
	86, 88, 89, 109, 150, 89, 109, 89, 90, 109,
	89, 109, 90, 149, 90, 148, 105, 90, 96, 96,
	96, 96, 90, 103, 96, 98, 98, 98, 96, 102,
	97, 98, 91, 52, 46, 98, 100, 100, 100, 100,
	104, 104, 104, 104, 106, 106, 106, 107, 45, 43,

	106, 108, 39, 108, 106, 37, 108, 107, 18, 17,
	107, 108, 16, 110, 111, 107, 110, 111, 15, 110,
	111, 110, 111, 112, 113, 114, 112, 113, 14, 115,
	12, 112, 113, 115, 7, 114, 115, 2, 114, 0,
	0, 115, 116, 114, 0, 116, 116, 117, 0, 118,
	116, 117, 118, 117, 119, 0, 117, 118, 120, 0,
	119, 117, 122, 119, 121, 0, 120, 121, 119, 120,
	122, 121, 121, 122, 120, 0, 123, 0, 122, 123,
	124, 124, 125, 124, 123, 125, 126, 0, 124, 126,
	125, 0, 127, 128, 126, 127, 128, 0, 0, 129,

	127, 128, 129, 129, 131, 130, 131, 129, 130, 131,
	0, 0, 130, 130, 131, 132, 134, 133, 132, 133,
	133, 134, 0, 132, 134, 133, 0, 135, 136, 134,
	135, 136, 137, 135, 0, 135, 136, 0, 138, 0,
	139, 138, 137, 139, 141, 137, 138, 140, 139, 0,
	137, 142, 0, 140, 0, 141, 140, 142, 141, 0,
	142, 140, 144, 141, 143, 142, 143, 143, 144, 0,
	0, 144, 143, 0, 0, 145, 144, 145, 145, 146,
	0, 146, 146, 145, 0, 147, 0, 146, 147, 151,
	151, 151, 151, 147, 153, 153, 153, 215, 215, 215,

	153, 0, 0, 215, 153, 157, 157, 157, 157, 0,
	0, 157, 158, 158, 158, 157, 0, 0, 158, 159,
	159, 159, 158, 0, 0, 159, 0, 0, 0, 159,
	161, 161, 161, 161, 162, 0, 163, 162, 163, 163,
	162, 164, 162, 166, 163, 165, 166, 164, 165, 168,
	164, 166, 165, 165, 167, 164, 0, 169, 167, 168,
	169, 167, 168, 0, 0, 169, 167, 168, 170, 171,
	170, 170, 171, 0, 173, 172, 170, 171, 172, 173,
	0, 174, 173, 172, 174, 174, 0, 173, 175, 174,
	176, 175, 0, 176, 177, 0, 175, 177, 176, 178,

	177, 179, 178, 180, 179, 177, 180, 178, 183, 179,
	181, 180, 182, 181, 184, 182, 183, 184, 181, 183,
	182, 187, 184, 185, 183, 186, 185, 187, 186, 188,
	187, 185, 188, 186, 188, 187, 0, 188, 189, 189,
	190, 189, 191, 190, 0, 191, 189, 191, 190, 192,
	191, 193, 192, 194, 192, 195, 0, 192, 195, 193,
	0, 194, 193, 195, 194, 196, 0, 193, 196, 194,
	197, 198, 197, 196, 198, 197, 199, 0, 0, 198,
	197, 0, 199, 0, 0, 199, 204, 204, 204, 204,
	199, 0, 204, 205, 205, 205, 204, 0, 0, 205,

	206, 206, 206, 205, 0, 0, 206, 0, 0, 0,
	206, 208, 208, 208, 208, 213, 213, 213, 213, 216,
	217, 218, 216, 217, 218, 219, 0, 216, 217, 218,
	0, 220, 0, 0, 220, 219, 220, 221, 219, 220,
	221, 222, 0, 219, 222, 221, 222, 223, 224, 222,
	223, 224, 0, 0, 225, 223, 224, 225, 226, 0,
	227, 226, 225, 227, 229, 226, 226, 227, 227, 228,
	229, 230, 228, 229, 230, 232, 230, 228, 229, 230,
	231, 236, 232, 231, 236, 232, 233, 236, 231, 236,
	232, 234, 233, 0, 234, 233, 0, 0, 234, 234,

	233, 235, 237, 235, 235, 237, 0, 0, 238, 235,
	237, 238, 0, 0, 0, 238, 238, 239, 240, 239,
	239, 240, 0, 0, 0, 239, 240, 246, 246, 246,
	246, 248, 248, 248, 0, 0, 0, 248, 254, 254,
	254, 254, 0, 0, 254, 255, 255, 255, 256, 256,
	256, 255, 0, 258, 256, 258, 258, 259, 260, 0,
	259, 258, 0, 261, 260, 259, 261, 260, 0, 0,
	261, 261, 260, 262, 0, 263, 262, 263, 264, 262,
	263, 262, 0, 265, 264, 263, 265, 264, 269, 0,
	0, 265, 264, 266, 266, 267, 266, 268, 267, 269,

	268, 266, 269, 267, 271, 268, 270, 269, 272, 270,
	271, 272, 273, 271, 270, 273, 272, 274, 271, 0,
	273, 274, 0, 0, 274, 281, 281, 281, 281, 274,
	0, 281, 282, 282, 282, 283, 283, 283, 282, 289,
	290, 283, 289, 290, 0, 0, 289, 289, 290, 291,
	0, 292, 291, 293, 292, 0, 293, 291, 292, 292,
	294, 293, 295, 294, 296, 295, 297, 296, 294, 297,
	295, 0, 296, 298, 297, 298, 298, 299, 0, 309,
	299, 298, 309, 0, 310, 299, 310, 309, 311, 310,
	311, 311, 0, 312, 310, 312, 311, 313, 312, 321,

	313, 323, 0, 312, 313, 313, 322, 321, 323, 322,
	321, 323, 0, 0, 322, 321, 323, 324, 330, 331,
	324, 330, 331, 0, 330, 324, 330, 331, 335, 0,
	0, 335, 0, 0, 0, 0, 335, 338, 338, 338,
	338, 338, 338, 338, 338, 339, 339, 339, 339, 339,
	339, 339, 339, 340, 340, 340, 340, 340, 340, 340,
	340, 341, 341, 341, 0, 341, 0, 341, 342, 342,
	342, 342, 342, 342, 0, 342, 343, 343, 0, 343,
	343, 343, 343, 343, 344, 344, 344, 344, 344, 344,
	344, 344, 345, 345, 0, 0, 345, 345, 345, 345,

	346, 346, 346, 346, 347, 347, 347, 347, 348, 348,
	348, 348, 348, 348, 348, 348, 349, 349, 349, 0,
	349, 0, 349, 350, 350, 350, 350, 350, 350, 350,
	350, 351, 351, 351, 0, 351, 0, 351, 352, 352,
	352, 352, 353, 353, 353, 353, 354, 354, 354, 354,
	354, 354, 354, 354, 355, 355, 355, 0, 355, 356,
	356, 356, 356, 356, 356, 356, 356, 357, 357, 357,
	0, 357, 337, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,

	337, 337, 337, 337, 337, 337, 337, 337, 337, 337,
	337, 337, 337, 337
};

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char	   *yytext;

#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"
/**********************************************************************
 * scan.l		- Scanner for the PL/pgSQL
 *			  procedural language
 *
 * IDENTIFICATION
 *	  $Header: /home/rubik/work/pgcvs/CVSROOT/pgsql/src/pl/plpgsql/src/Attic/pl_scan.c,v 1.1.2.1 2003-09-07 22:51:55 momjian Exp $
 *
 *	  This software is copyrighted by Jan Wieck - Hamburg.
 *
 *	  The author hereby grants permission  to  use,  copy,	modify,
 *	  distribute,  and	license this software and its documentation
 *	  for any purpose, provided that existing copyright notices are
 *	  retained	in	all  copies  and  that	this notice is included
 *	  verbatim in any distributions. No written agreement, license,
 *	  or  royalty  fee	is required for any of the authorized uses.
 *	  Modifications to this software may be  copyrighted  by  their
 *	  author  and  need  not  follow  the licensing terms described
 *	  here, provided that the new terms are  clearly  indicated  on
 *	  the first page of each file where they apply.
 *
 *	  IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTORS BE LIABLE TO ANY
 *	  PARTY  FOR  DIRECT,	INDIRECT,	SPECIAL,   INCIDENTAL,	 OR
 *	  CONSEQUENTIAL   DAMAGES  ARISING	OUT  OF  THE  USE  OF  THIS
 *	  SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF, EVEN
 *	  IF  THE  AUTHOR  HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
 *	  DAMAGE.
 *
 *	  THE  AUTHOR  AND	DISTRIBUTORS  SPECIFICALLY	 DISCLAIM	ANY
 *	  WARRANTIES,  INCLUDING,  BUT	NOT  LIMITED  TO,  THE	IMPLIED
 *	  WARRANTIES  OF  MERCHANTABILITY,	FITNESS  FOR  A  PARTICULAR
 *	  PURPOSE,	AND NON-INFRINGEMENT.  THIS SOFTWARE IS PROVIDED ON
 *	  AN "AS IS" BASIS, AND THE AUTHOR	AND  DISTRIBUTORS  HAVE  NO
 *	  OBLIGATION   TO	PROVIDE   MAINTENANCE,	 SUPPORT,  UPDATES,
 *	  ENHANCEMENTS, OR MODIFICATIONS.
 *
 **********************************************************************/

#include "plpgsql.h"


/* No reason to constrain amount of data slurped */
#define YY_READ_BUF_SIZE 16777216

/* Avoid exit() on fatal scanner errors (a bit ugly -- see yy_fatal_error) */
#define fprintf(file, fmt, msg)  ereport(ERROR, (errmsg_internal("%s", msg)))

/* Handles to the buffer that the lexer uses internally */
static YY_BUFFER_STATE scanbufhandle;
static char *scanbuf;

static int	scanner_functype;
static int	scanner_typereported;
static int	pushback_token;
static bool have_pushback_token;
static int	lookahead_token;
static bool have_lookahead_token;
static const char *cur_line_start;
static int	cur_line_num;

int			plpgsql_SpaceScanned = 0;

#define YY_NEVER_INTERACTIVE 1
#define YY_NO_UNPUT 1
#define IN_STRING 1
#define IN_COMMENT 2

#line 854 "pl_scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern		"C" int yywrap YY_PROTO((void));

#else
extern int yywrap YY_PROTO((void));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO((int c, char *buf_ptr));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO((char *, yyconst char *, int));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO((yyconst char *));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO((void));

#else
static int input YY_PROTO((void));
#endif
#endif

#if YY_STACK_USED
static int	yy_start_stack_ptr = 0;
static int	yy_start_stack_depth = 0;
static int *yy_start_stack = 0;

#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO((int new_state));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO((void));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO((void));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
				 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp,
			   *yy_bp;
	register int yy_act;

#line 86 "scan.l"

	/* ----------
	 * Local variables in scanner to remember where
	 * a string or comment started
	 * ----------
	 */
	int			start_lineno = 0;
	char	   *start_charpos = NULL;

	/* ----------
	 * Reset the state when entering the scanner
	 * ----------
	 */
	BEGIN		INITIAL;

	plpgsql_SpaceScanned = 0;

	/* ----------
	 * On the first call to a new source report the
	 * functions type (T_FUNCTION or T_TRIGGER)
	 * ----------
	 */
	if (!scanner_typereported)
	{
		scanner_typereported = 1;
		return scanner_functype;
	}

	/* ----------
	 * The keyword rules
	 * ----------
	 */
#line 1040 "pl_scan.c"

	if (yy_init)
	{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if (!yy_start)
			yy_start = 1;		/* first start state */

		if (!yyin)
			yyin = stdin;

		if (!yyout)
			yyout = stdout;

		if (!yy_current_buffer)
			yy_current_buffer =
				yy_create_buffer(yyin, YY_BUF_SIZE);

		yy_load_buffer_state();
	}

	while (1)					/* loops until end-of-file is reached */
	{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/*
		 * yy_bp points to the position in yy_ch_buf of the start of the
		 * current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
		{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];

			if (yy_accept[yy_current_state])
			{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
			}
			while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
			{
				yy_current_state = (int) yy_def[yy_current_state];
				if (yy_current_state >= 338)
					yy_c = yy_meta[(unsigned int) yy_c];
			}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
		}
		while (yy_base[yy_current_state] != 1273);

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if (yy_act == 0)
		{						/* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
		}

		YY_DO_BEFORE_ACTION;


do_action:						/* This label is used only to access EOF
								 * actions. */


		switch (yy_act)
		{						/* beginning of action switch */
			case 0:				/* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = yy_hold_char;
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;

			case 1:
				YY_RULE_SETUP
#line 117 "scan.l"
					return K_ASSIGN;
				YY_BREAK
			case 2:
				YY_RULE_SETUP
#line 118 "scan.l"
					return K_ASSIGN;
				YY_BREAK
			case 3:
				YY_RULE_SETUP
#line 119 "scan.l"
					return K_DOTDOT;
				YY_BREAK
			case 4:
				YY_RULE_SETUP
#line 120 "scan.l"
					return K_ALIAS;
				YY_BREAK
			case 5:
				YY_RULE_SETUP
#line 121 "scan.l"
					return K_BEGIN;
				YY_BREAK
			case 6:
				YY_RULE_SETUP
#line 122 "scan.l"
					return K_CLOSE;
				YY_BREAK
			case 7:
				YY_RULE_SETUP
#line 123 "scan.l"
					return K_CONSTANT;
				YY_BREAK
			case 8:
				YY_RULE_SETUP
#line 124 "scan.l"
					return K_CURSOR;
				YY_BREAK
			case 9:
				YY_RULE_SETUP
#line 125 "scan.l"
					return K_DEBUG;
				YY_BREAK
			case 10:
				YY_RULE_SETUP
#line 126 "scan.l"
					return K_DECLARE;
				YY_BREAK
			case 11:
				YY_RULE_SETUP
#line 127 "scan.l"
					return K_DEFAULT;
				YY_BREAK
			case 12:
				YY_RULE_SETUP
#line 128 "scan.l"
					return K_DIAGNOSTICS;
				YY_BREAK
			case 13:
				YY_RULE_SETUP
#line 129 "scan.l"
					return K_ELSE;
				YY_BREAK
			case 14:
				YY_RULE_SETUP
#line 130 "scan.l"
					return K_ELSIF;
				YY_BREAK
			case 15:
				YY_RULE_SETUP
#line 131 "scan.l"
					return K_END;
				YY_BREAK
			case 16:
				YY_RULE_SETUP
#line 132 "scan.l"
					return K_EXCEPTION;
				YY_BREAK
			case 17:
				YY_RULE_SETUP
#line 133 "scan.l"
					return K_EXECUTE;
				YY_BREAK
			case 18:
				YY_RULE_SETUP
#line 134 "scan.l"
					return K_EXIT;
				YY_BREAK
			case 19:
				YY_RULE_SETUP
#line 135 "scan.l"
					return K_FETCH;
				YY_BREAK
			case 20:
				YY_RULE_SETUP
#line 136 "scan.l"
					return K_FOR;
				YY_BREAK
			case 21:
				YY_RULE_SETUP
#line 137 "scan.l"
					return K_FROM;
				YY_BREAK
			case 22:
				YY_RULE_SETUP
#line 138 "scan.l"
					return K_GET;
				YY_BREAK
			case 23:
				YY_RULE_SETUP
#line 139 "scan.l"
					return K_IF;
				YY_BREAK
			case 24:
				YY_RULE_SETUP
#line 140 "scan.l"
					return K_IN;
				YY_BREAK
			case 25:
				YY_RULE_SETUP
#line 141 "scan.l"
					return K_INFO;
				YY_BREAK
			case 26:
				YY_RULE_SETUP
#line 142 "scan.l"
					return K_INTO;
				YY_BREAK
			case 27:
				YY_RULE_SETUP
#line 143 "scan.l"
					return K_IS;
				YY_BREAK
			case 28:
				YY_RULE_SETUP
#line 144 "scan.l"
					return K_LOG;
				YY_BREAK
			case 29:
				YY_RULE_SETUP
#line 145 "scan.l"
					return K_LOOP;
				YY_BREAK
			case 30:
				YY_RULE_SETUP
#line 146 "scan.l"
					return K_NEXT;
				YY_BREAK
			case 31:
				YY_RULE_SETUP
#line 147 "scan.l"
					return K_NOT;
				YY_BREAK
			case 32:
				YY_RULE_SETUP
#line 148 "scan.l"
					return K_NOTICE;
				YY_BREAK
			case 33:
				YY_RULE_SETUP
#line 149 "scan.l"
					return K_NULL;
				YY_BREAK
			case 34:
				YY_RULE_SETUP
#line 150 "scan.l"
					return K_OPEN;
				YY_BREAK
			case 35:
				YY_RULE_SETUP
#line 151 "scan.l"
					return K_PERFORM;
				YY_BREAK
			case 36:
				YY_RULE_SETUP
#line 152 "scan.l"
					return K_RAISE;
				YY_BREAK
			case 37:
				YY_RULE_SETUP
#line 153 "scan.l"
					return K_RECORD;
				YY_BREAK
			case 38:
				YY_RULE_SETUP
#line 154 "scan.l"
					return K_RENAME;
				YY_BREAK
			case 39:
				YY_RULE_SETUP
#line 155 "scan.l"
					return K_RESULT_OID;
				YY_BREAK
			case 40:
				YY_RULE_SETUP
#line 156 "scan.l"
					return K_RETURN;
				YY_BREAK
			case 41:
				YY_RULE_SETUP
#line 157 "scan.l"
					return K_REVERSE;
				YY_BREAK
			case 42:
				YY_RULE_SETUP
#line 158 "scan.l"
					return K_ROW_COUNT;
				YY_BREAK
			case 43:
				YY_RULE_SETUP
#line 159 "scan.l"
					return K_SELECT;
				YY_BREAK
			case 44:
				YY_RULE_SETUP
#line 160 "scan.l"
					return K_THEN;
				YY_BREAK
			case 45:
				YY_RULE_SETUP
#line 161 "scan.l"
					return K_TO;
				YY_BREAK
			case 46:
				YY_RULE_SETUP
#line 162 "scan.l"
					return K_TYPE;
				YY_BREAK
			case 47:
				YY_RULE_SETUP
#line 163 "scan.l"
					return K_WARNING;
				YY_BREAK
			case 48:
				YY_RULE_SETUP
#line 164 "scan.l"
					return K_WHEN;
				YY_BREAK
			case 49:
				YY_RULE_SETUP
#line 165 "scan.l"
					return K_WHILE;
				YY_BREAK
			case 50:
				YY_RULE_SETUP
#line 167 "scan.l"
					return O_OPTION;
				YY_BREAK
			case 51:
				YY_RULE_SETUP
#line 168 "scan.l"
					return O_DUMP;
				YY_BREAK
/* ----------
	 * Special word rules
	 *
	 * We set plpgsql_error_lineno in each rule so that errors reported
	 * in the pl_comp.c subroutines will point to the right place.
	 * ----------
	 */
			case 52:
				YY_RULE_SETUP
#line 178 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_word(yytext);
				}
				YY_BREAK
			case 53:
				YY_RULE_SETUP
#line 181 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_dblword(yytext);
				}
				YY_BREAK
			case 54:
				YY_RULE_SETUP
#line 184 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_tripword(yytext);
				}
				YY_BREAK
			case 55:
				YY_RULE_SETUP
#line 187 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_wordtype(yytext);
				}
				YY_BREAK
			case 56:
				YY_RULE_SETUP
#line 190 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_dblwordtype(yytext);
				}
				YY_BREAK
			case 57:
				YY_RULE_SETUP
#line 193 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_tripwordtype(yytext);
				}
				YY_BREAK
			case 58:
				YY_RULE_SETUP
#line 196 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_wordrowtype(yytext);
				}
				YY_BREAK
			case 59:
				YY_RULE_SETUP
#line 199 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_dblwordrowtype(yytext);
				}
				YY_BREAK
			case 60:
				YY_RULE_SETUP
#line 202 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_word(yytext);
				}
				YY_BREAK
			case 61:
				YY_RULE_SETUP
#line 205 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_dblword(yytext);
				}
				YY_BREAK
			case 62:
				YY_RULE_SETUP
#line 208 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_tripword(yytext);
				}
				YY_BREAK
			case 63:
				YY_RULE_SETUP
#line 211 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_wordtype(yytext);
				}
				YY_BREAK
			case 64:
				YY_RULE_SETUP
#line 214 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_dblwordtype(yytext);
				}
				YY_BREAK
			case 65:
				YY_RULE_SETUP
#line 217 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_tripwordtype(yytext);
				}
				YY_BREAK
			case 66:
				YY_RULE_SETUP
#line 220 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_wordrowtype(yytext);
				}
				YY_BREAK
			case 67:
				YY_RULE_SETUP
#line 223 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					return plpgsql_parse_dblwordrowtype(yytext);
				}
				YY_BREAK
			case 68:
				YY_RULE_SETUP
#line 227 "scan.l"
					return T_NUMBER;
				YY_BREAK
			case 69:
				YY_RULE_SETUP
#line 229 "scan.l"
				{
					plpgsql_error_lineno = plpgsql_scanner_lineno();
					ereport(ERROR,
							(errcode(ERRCODE_DATATYPE_MISMATCH),
							 errmsg("unterminated quoted identifier")));
				}
				YY_BREAK
/* ----------
	 * Ignore whitespaces but remember this happened
	 * ----------
	 */
			case 70:
				YY_RULE_SETUP
#line 240 "scan.l"
					plpgsql_SpaceScanned = 1;
				YY_BREAK
/* ----------
	 * Eat up comments
	 * ----------
	 */
			case 71:
				YY_RULE_SETUP
#line 246 "scan.l"
					;
				YY_BREAK
			case 72:
				YY_RULE_SETUP
#line 248 "scan.l"
				{
					start_lineno = plpgsql_scanner_lineno();
					BEGIN		IN_COMMENT;
				}
				YY_BREAK
			case 73:
				YY_RULE_SETUP
#line 251 "scan.l"
				{
					BEGIN		INITIAL;

					plpgsql_SpaceScanned = 1;
				}
				YY_BREAK
			case 74:
				YY_RULE_SETUP
#line 252 "scan.l"
					;
				YY_BREAK
			case 75:
				YY_RULE_SETUP
#line 253 "scan.l"
					;
				YY_BREAK
			case YY_STATE_EOF(IN_COMMENT):
#line 254 "scan.l"
				{
					plpgsql_error_lineno = start_lineno;
					ereport(ERROR,
							(errcode(ERRCODE_DATATYPE_MISMATCH),
							 errmsg("unterminated comment")));
				}
				YY_BREAK
/* ----------
	 * Collect anything inside of ''s and return one STRING
	 *
	 * Hacking yytext/yyleng here lets us avoid using yymore(), which is
	 * a win for performance.  It's safe because we know the underlying
	 * input buffer is not changing.
	 * ----------
	 */
			case 76:
				YY_RULE_SETUP
#line 269 "scan.l"
				{
					start_lineno = plpgsql_scanner_lineno();
					start_charpos = yytext;
					BEGIN		IN_STRING;
				}
				YY_BREAK
			case 77:
				YY_RULE_SETUP
#line 274 "scan.l"
				{
				}
				YY_BREAK
			case 78:
				YY_RULE_SETUP
#line 275 "scan.l"
				{
				}
				YY_BREAK
			case 79:
				YY_RULE_SETUP
#line 276 "scan.l"
				{
					yyleng -= (yytext - start_charpos);
					yytext = start_charpos;
					BEGIN		INITIAL;

					return T_STRING;
				}
				YY_BREAK
			case YY_STATE_EOF(IN_STRING):
#line 282 "scan.l"
				{
					plpgsql_error_lineno = start_lineno;
					ereport(ERROR,
							(errcode(ERRCODE_DATATYPE_MISMATCH),
							 errmsg("unterminated string")));
				}
				YY_BREAK
			case 80:
				YY_RULE_SETUP
#line 288 "scan.l"
				{
				}
				YY_BREAK
/* ----------
	 * Any unmatched character is returned as is
	 * ----------
	 */
			case 81:
				YY_RULE_SETUP
#line 294 "scan.l"
					return yytext[0];
				YY_BREAK
			case 82:
				YY_RULE_SETUP
#line 296 "scan.l"
					ECHO;
				YY_BREAK
#line 1627 "pl_scan.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

			case YY_END_OF_BUFFER:
				{
					/* Amount of text matched not including the EOB char. */
					int			yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

					/* Undo the effects of YY_DO_BEFORE_ACTION. */
					*yy_cp = yy_hold_char;
					YY_RESTORE_YY_MORE_OFFSET

						if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW)
					{
						/*
						 * We're scanning a new file or input source.
						 * It's possible that this happened because the
						 * user just pointed yyin at a new source and
						 * called yylex().	If so, then we have to assure
						 * consistency between yy_current_buffer and our
						 * globals.  Here is the right place to do so,
						 * because this is the first action (other than
						 * possibly a back-up) that will match for the new
						 * input source.
						 */
						yy_n_chars = yy_current_buffer->yy_n_chars;
						yy_current_buffer->yy_input_file = yyin;
						yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
					}

					/*
					 * Note that here we test for yy_c_buf_p "<=" to the
					 * position of the first EOB in the buffer, since
					 * yy_c_buf_p will already have been incremented past
					 * the NUL character (since all states make
					 * transitions on EOB to the end-of-buffer state).
					 * Contrast this with the test in input().
					 */
					if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
					{			/* This was really a NUL. */
						yy_state_type yy_next_state;

						yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state();

						/*
						 * Okay, we're now positioned to make the NUL
						 * transition.	We couldn't have
						 * yy_get_previous_state() go ahead and do it for
						 * us because it doesn't know how to deal with the
						 * possibility of jamming (and we don't want to
						 * build jamming into it because then it will run
						 * more slowly).
						 */

						yy_next_state = yy_try_NUL_trans(yy_current_state);

						yy_bp = yytext_ptr + YY_MORE_ADJ;

						if (yy_next_state)
						{
							/* Consume the NUL. */
							yy_cp = ++yy_c_buf_p;
							yy_current_state = yy_next_state;
							goto yy_match;
						}

						else
						{
							yy_cp = yy_c_buf_p;
							goto yy_find_action;
						}
					}

					else
						switch (yy_get_next_buffer())
						{
							case EOB_ACT_END_OF_FILE:
								{
									yy_did_buffer_switch_on_eof = 0;

									if (yywrap())
									{
										/*
										 * Note: because we've taken care
										 * in yy_get_next_buffer() to have
										 * set up yytext, we can now set
										 * up yy_c_buf_p so that if some
										 * total hoser (like flex itself)
										 * wants to call the scanner after
										 * we return the YY_NULL, it'll
										 * still work - another YY_NULL
										 * will get returned.
										 */
										yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

										yy_act = YY_STATE_EOF(YY_START);
										goto do_action;
									}

									else
									{
										if (!yy_did_buffer_switch_on_eof)
											YY_NEW_FILE;
									}
									break;
								}

							case EOB_ACT_CONTINUE_SCAN:
								yy_c_buf_p =
									yytext_ptr + yy_amount_of_matched_text;

								yy_current_state = yy_get_previous_state();

								yy_cp = yy_c_buf_p;
								yy_bp = yytext_ptr + YY_MORE_ADJ;
								goto yy_match;

							case EOB_ACT_LAST_MATCH:
								yy_c_buf_p =
									&yy_current_buffer->yy_ch_buf[yy_n_chars];

								yy_current_state = yy_get_previous_state();

								yy_cp = yy_c_buf_p;
								yy_bp = yytext_ptr + YY_MORE_ADJ;
								goto yy_find_action;
						}
					break;
				}

			default:
				YY_FATAL_ERROR(
				   "fatal flex scanner internal error--no action found");
		}						/* end of action switch */
	}							/* end of scanning one token */
}	/* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int
yy_get_next_buffer()
{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move,
				i;
	int			ret_val;

	if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
		YY_FATAL_ERROR(
			  "fatal flex scanner internal error--end of buffer missed");

	if (yy_current_buffer->yy_fill_buffer == 0)
	{							/* Don't try to fill the buffer, so this
								 * is an EOF. */
		if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
		{
			/*
			 * We matched a single character, the EOB, so treat this as a
			 * final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		}

		else
		{
			/*
			 * We matched some text prior to the EOB, first process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for (i = 0; i < number_to_move; ++i)
		*(dest++) = *(source++);

	if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)

		/*
		 * don't do the read, it's not guaranteed to return an EOF, just
		 * force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
	{
		int			num_to_read =
		yy_current_buffer->yy_buf_size - number_to_move - 1;

		while (num_to_read <= 0)
		{						/* Not enough room in the buffer - grow
								 * it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
						   "input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int			yy_c_buf_p_offset =
			(int) (yy_c_buf_p - b->yy_ch_buf);

			if (b->yy_is_our_buffer)
			{
				int			new_size = b->yy_buf_size * 2;

				if (new_size <= 0)
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
				/* Include room in for 2 EOB chars. */
					yy_flex_realloc((void *) b->yy_ch_buf,
									b->yy_buf_size + 2);
			}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if (!b->yy_ch_buf)
				YY_FATAL_ERROR(
						  "fatal error - scanner input buffer overflow");

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
				number_to_move - 1;
#endif
		}

		if (num_to_read > YY_READ_BUF_SIZE)
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT((&yy_current_buffer->yy_ch_buf[number_to_move]),
				 yy_n_chars, num_to_read);

		yy_current_buffer->yy_n_chars = yy_n_chars;
	}

	if (yy_n_chars == 0)
	{
		if (number_to_move == YY_MORE_ADJ)
		{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin);
		}

		else
		{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type
yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp)
	{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);

		if (yy_accept[yy_current_state])
		{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
		}
		while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
		{
			yy_current_state = (int) yy_def[yy_current_state];
			if (yy_current_state >= 338)
				yy_c = yy_meta[(unsigned int) yy_c];
		}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	}

	return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type
yy_try_NUL_trans(yy_state_type yy_current_state)
#else
static yy_state_type
yy_try_NUL_trans(yy_current_state)
yy_state_type yy_current_state;
#endif
{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;

	if (yy_accept[yy_current_state])
	{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
	}
	while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	{
		yy_current_state = (int) yy_def[yy_current_state];
		if (yy_current_state >= 338)
			yy_c = yy_meta[(unsigned int) yy_c];
	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 337);

	return yy_is_jam ? 0 : yy_current_state;
}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void
yyunput(int c, register char *yy_bp)
#else
static void
yyunput(c, yy_bp)
int			c;
register char *yy_bp;
#endif
{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
	{							/* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
									 yy_current_buffer->yy_buf_size + 2];
		register char *source =
		&yy_current_buffer->yy_ch_buf[number_to_move];

		while (source > yy_current_buffer->yy_ch_buf)
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
			YY_FATAL_ERROR("flex scanner push-back overflow");
	}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
}
#endif   /* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int
yyinput()
#else
static int
input()
#endif
{
	int			c;

	*yy_c_buf_p = yy_hold_char;

	if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
	{
		/*
		 * yy_c_buf_p now points to the character we want to return. If
		 * this occurs *before* the EOB characters, then it's a valid NUL;
		 * if not, then we've hit the end of the buffer.
		 */
		if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
		{						/* need more input */
			int			offset = yy_c_buf_p - yytext_ptr;

			++yy_c_buf_p;

			switch (yy_get_next_buffer())
			{
				case EOB_ACT_LAST_MATCH:

					/*
					 * This happens because yy_g_n_b() sees that we've
					 * accumulated a token and flags that we need to try
					 * matching the token before proceeding.  But for
					 * input(), there's no matching to consider. So
					 * convert the EOB_ACT_LAST_MATCH to
					 * EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin);

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
						if (yywrap())
							return EOF;

						if (!yy_did_buffer_switch_on_eof)
							YY_NEW_FILE;
#ifdef __cplusplus
						return yyinput();
#else
						return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
			}
		}
	}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';			/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
}


#ifdef YY_USE_PROTOS
void
yyrestart(FILE *input_file)
#else
void
yyrestart(input_file)
FILE	   *input_file;
#endif
{
	if (!yy_current_buffer)
		yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE);

	yy_init_buffer(yy_current_buffer, input_file);
	yy_load_buffer_state();
}


#ifdef YY_USE_PROTOS
void
yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
#else
void
yy_switch_to_buffer(new_buffer)
YY_BUFFER_STATE new_buffer;
#endif
{
	if (yy_current_buffer == new_buffer)
		return;

	if (yy_current_buffer)
	{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
	}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/*
	 * We don't actually know whether we did this switch during EOF
	 * (yywrap()) processing, but the only time this flag is looked at is
	 * after yywrap() is called, so it's safe to go ahead and always set
	 * it.
	 */
	yy_did_buffer_switch_on_eof = 1;
}


#ifdef YY_USE_PROTOS
void
yy_load_buffer_state(void)
#else
void
yy_load_buffer_state()
#endif
{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_create_buffer(FILE *file, int size)
#else
YY_BUFFER_STATE
yy_create_buffer(file, size)
FILE	   *file;
int			size;
#endif
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc(sizeof(struct yy_buffer_state));
	if (!b)
		YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

	b->yy_buf_size = size;

	/*
	 * yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc(b->yy_buf_size + 2);
	if (!b->yy_ch_buf)
		YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b, file);

	return b;
}


#ifdef YY_USE_PROTOS
void
yy_delete_buffer(YY_BUFFER_STATE b)
#else
void
yy_delete_buffer(b)
YY_BUFFER_STATE b;
#endif
{
	if (!b)
		return;

	if (b == yy_current_buffer)
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if (b->yy_is_our_buffer)
		yy_flex_free((void *) b->yy_ch_buf);

	yy_flex_free((void *) b);
}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO((int));
#endif
#endif

#ifdef YY_USE_PROTOS
void
yy_init_buffer(YY_BUFFER_STATE b, FILE *file)
#else
void
yy_init_buffer(b, file)
YY_BUFFER_STATE b;
FILE	   *file;
#endif


{
	yy_flush_buffer(b);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;
#endif
#endif
}


#ifdef YY_USE_PROTOS
void
yy_flush_buffer(YY_BUFFER_STATE b)
#else
void
yy_flush_buffer(b)
YY_BUFFER_STATE b;
#endif

{
	if (!b)
		return;

	b->yy_n_chars = 0;

	/*
	 * We always need two end-of-buffer characters.  The first causes a
	 * transition to the end-of-buffer state.  The second causes a jam in
	 * that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if (b == yy_current_buffer)
		yy_load_buffer_state();
}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_buffer(char *base, yy_size_t size)
#else
YY_BUFFER_STATE
yy_scan_buffer(base, size)
char	   *base;
yy_size_t	size;
#endif
{
	YY_BUFFER_STATE b;

	if (size < 2 ||
		base[size - 2] != YY_END_OF_BUFFER_CHAR ||
		base[size - 1] != YY_END_OF_BUFFER_CHAR)
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc(sizeof(struct yy_buffer_state));
	if (!b)
		YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b);

	return b;
}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_string(yyconst char *yy_str)
#else
YY_BUFFER_STATE
yy_scan_string(yy_str)
yyconst char *yy_str;
#endif
{
	int			len;

	for (len = 0; yy_str[len]; ++len)
		;

	return yy_scan_bytes(yy_str, len);
}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_bytes(yyconst char *bytes, int len)
#else
YY_BUFFER_STATE
yy_scan_bytes(bytes, len)
yyconst char *bytes;
int			len;
#endif
{
	YY_BUFFER_STATE b;
	char	   *buf;
	yy_size_t	n;
	int			i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc(n);
	if (!buf)
		YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

	for (i = 0; i < len; ++i)
		buf[i] = bytes[i];

	buf[len] = buf[len + 1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf, n);
	if (!b)
		YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

	/*
	 * It's okay to grow etc. this buffer, and we should throw it away
	 * when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void
yy_push_state(int new_state)
#else
static void
yy_push_state(new_state)
int			new_state;
#endif
{
	if (yy_start_stack_ptr >= yy_start_stack_depth)
	{
		yy_size_t	new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof(int);

		if (!yy_start_stack)
			yy_start_stack = (int *) yy_flex_alloc(new_size);

		else
			yy_start_stack = (int *) yy_flex_realloc(
									  (void *) yy_start_stack, new_size);

		if (!yy_start_stack)
			YY_FATAL_ERROR(
						"out of memory expanding start-condition stack");
	}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
}
#endif


#ifndef YY_NO_POP_STATE
static void
yy_pop_state()
{
	if (--yy_start_stack_ptr < 0)
		YY_FATAL_ERROR("start-condition stack underflow");

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif


#ifndef YY_NO_TOP_STATE
static int
yy_top_state()
{
	return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void
yy_fatal_error(yyconst char msg[])
#else
static void
yy_fatal_error(msg)
char		msg[];
#endif
{
	(void) fprintf(stderr, "%s\n", msg);
	exit(YY_EXIT_FAILURE);
}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void
yy_flex_strncpy(char *s1, yyconst char *s2, int n)
#else
static void
yy_flex_strncpy(s1, s2, n)
char	   *s1;
yyconst char *s2;
int			n;
#endif
{
	register int i;

	for (i = 0; i < n; ++i)
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int
yy_flex_strlen(yyconst char *s)
#else
static int
yy_flex_strlen(s)
yyconst char *s;
#endif
{
	register int n;

	for (n = 0; s[n]; ++n)
		;

	return n;
}
#endif


#ifdef YY_USE_PROTOS
static void *
yy_flex_alloc(yy_size_t size)
#else
static void *
yy_flex_alloc(size)
yy_size_t	size;
#endif
{
	return (void *) malloc(size);
}

#ifdef YY_USE_PROTOS
static void *
yy_flex_realloc(void *ptr, yy_size_t size)
#else
static void *
yy_flex_realloc(ptr, size)
void	   *ptr;
yy_size_t	size;
#endif
{
	/*
	 * The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those that use
	 * void* generic pointers.	It works with the latter because both ANSI
	 * C and C++ allow castless assignment from any pointer type to void*,
	 * and deal with argument conversions as though doing an assignment.
	 */
	return (void *) realloc((char *) ptr, size);
}

#ifdef YY_USE_PROTOS
static void
yy_flex_free(void *ptr)
#else
static void
yy_flex_free(ptr)
void	   *ptr;
#endif
{
	free(ptr);
}

#if YY_MAIN
int
main()
{
	yylex();
	return 0;
}
#endif
#line 296 "scan.l"



/*
 * This is the yylex routine called from outside. It exists to provide
 * a pushback facility, as well as to allow us to parse syntax that
 * requires more than one token of lookahead.
 */
int
plpgsql_yylex(void)
{
	int			cur_token;

	if (have_pushback_token)
	{
		have_pushback_token = false;
		cur_token = pushback_token;
	}
	else if (have_lookahead_token)
	{
		have_lookahead_token = false;
		cur_token = lookahead_token;
	}
	else
		cur_token = yylex();

	/* Do we need to look ahead for a possible multiword token? */
	switch (cur_token)
	{
			/* RETURN NEXT must be reduced to a single token */
		case K_RETURN:
			if (!have_lookahead_token)
			{
				lookahead_token = yylex();
				have_lookahead_token = true;
			}
			if (lookahead_token == K_NEXT)
			{
				have_lookahead_token = false;
				cur_token = K_RETURN_NEXT;
			}
			break;

		default:
			break;
	}

	return cur_token;
}

/*
 * Push back a single token to be re-read by next plpgsql_yylex() call.
 */
void
plpgsql_push_back_token(int token)
{
	if (have_pushback_token)
		elog(ERROR, "cannot push back multiple tokens");
	pushback_token = token;
	have_pushback_token = true;
}

/*
 * Get the line number at which the current token ends.  This substitutes
 * for flex's very poorly implemented yylineno facility.
 *
 * We assume that flex has written a '\0' over the character following the
 * current token in scanbuf.  So, we just have to count the '\n' characters
 * before that.  We optimize this a little by keeping track of the last
 * '\n' seen so far.
 */
int
plpgsql_scanner_lineno(void)
{
	const char *c;

	while ((c = strchr(cur_line_start, '\n')) != NULL)
	{
		cur_line_start = c + 1;
		cur_line_num++;
	}
	return cur_line_num;
}

/*
 * Called before any actual parsing is done
 */
void
plpgsql_scanner_init(const char *str, int functype)
{
	Size		slen;

	/*----------
	 * Hack: skip any initial newline, so that in the common coding layout
	 *		CREATE FUNCTION ... AS '
	 *			code body
	 *		' LANGUAGE 'plpgsql';
	 * we will think "line 1" is what the programmer thinks of as line 1.
	 *----------
	 */
	if (*str == '\r')
		str++;
	if (*str == '\n')
		str++;

	slen = strlen(str);

	/*
	 * Might be left over after ereport()
	 */
	if (YY_CURRENT_BUFFER)
		yy_delete_buffer(YY_CURRENT_BUFFER);

	/*
	 * Make a scan buffer with special termination needed by flex.
	 */
	scanbuf = palloc(slen + 2);
	memcpy(scanbuf, str, slen);
	scanbuf[slen] = scanbuf[slen + 1] = YY_END_OF_BUFFER_CHAR;
	scanbufhandle = yy_scan_buffer(scanbuf, slen + 2);

	/* Other setup */
	scanner_functype = functype;
	scanner_typereported = 0;

	have_pushback_token = false;
	have_lookahead_token = false;

	cur_line_start = scanbuf;
	cur_line_num = 1;

	BEGIN(INITIAL);
}


/*
 * Called after parsing is done to clean up after plpgsql_scanner_init()
 */
void
plpgsql_scanner_finish(void)
{
	yy_delete_buffer(scanbufhandle);
	pfree(scanbuf);
}
