#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/smgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /home/rubik/work/pgcvs/CVSROOT/pgsql/src/backend/storage/smgr/Attic/Makefile.inc,v 1.1.1.1 1996-07-09 06:21:59 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= md.c mm.c smgr.c smgrtype.c
