#
# $Header: /home/rubik/work/pgcvs/CVSROOT/pgsql/contrib/tools/Attic/Makefile,v 1.3 2000-06-19 13:54:37 momjian Exp $
#

TOPDIR=../..

include ../Makefile.global

NAME	= 

PROGRAM	= 
OBJS	= 
DOCS	= 
SQLS	= 
BINS	=
EXAMPLES=
MODS	= 

clean:
	$(RM) *~ 

