#-------------------------------------------------------------------------
#
# Makefile for utils
#
# $Header: /home/rubik/work/pgcvs/CVSROOT/pgsql/src/utils/Attic/Makefile,v 1.15 2002-10-03 17:09:42 momjian Exp $
#
# dllinit.o is only built on Win32 platform.
#
#-------------------------------------------------------------------------

subdir = src/utils
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

all:

clean distclean maintainer-clean:
	rm -f dllinit.o getopt.o
