#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/large_object
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /home/rubik/work/pgcvs/CVSROOT/pgsql/src/backend/storage/large_object/Attic/Makefile.inc,v 1.1.1.1 1996-07-09 06:21:55 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= inv_api.c 
